<?php

class DataBase{
    
    
    public const DATA_BASE = 'jp_gis';
    
    public const PORT = '5432';
    
    public const HOST = '127.0.0.1';
    
    public const USER = 'postgres';
    
    public const PASS = '211074';
    
    public static $tableWithFiles = array(
        
    );
    
    public static $mergeFormColumnEspecialValue = array(
        
        
    );
    
    public static $passwordColumns = array(
        
    );
    
    public static $hiddenColumns = array(
        
    );
    
    public static $actionColumns = array(
        
    );
    
    public static $notNullColumns = array(
        
    );
    
    public static $tableViews = array(
        
    );
    
    public static $tableLabels = array(
        
    );
    
    public static $labels = array(
        
    );
    
    public static $isSpecialSQL = array(
        
    );
    
}

?>